create table productos(
id int auto_increment not null,
id_categoria int,
id_subcategoria int,
ruta text,
titulo text,
descripcion text,
detalle text,
precio int,
imagen text,
oferta boolean,
precioOferta int,
descuento int,
finOferta date,
fecha date,
publicada boolean,
stock int,
primary key (id),
foreign key(id_categoria) references categorias(id),
foreign key(id_subcategoria) references subcategorias(id));